"use client"

import { useState } from "react"
import AdminLayout from "@/components/admin-layout"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Search, Plus, Edit, Trash2, Filter } from "lucide-react"

interface PricelistItem {
  id: string
  productName: string
  productCode: string
  category: string
  unitPrice: number
  currency: string
  unit: string
  lastUpdated: string
  status: "active" | "inactive"
  msp?: number
  retailPrice?: number
  endCustomerPrice?: number
  mrp?: number
}

const mockPricelistData: PricelistItem[] = [
  // DINSTAR GSM- Volte Gateway (keeping existing data)
  {
    id: "1",
    productName: "2 Port GSM Volte Gateway",
    productCode: "UC-2000-VE-2T",
    category: "GSM/VoLTE Gateway",
    unitPrice: 26250,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 26250,
    retailPrice: 28875,
    endCustomerPrice: 31763,
    mrp: 34939,
  },
  {
    id: "2",
    productName: "4 Port GSM Volte Gateway",
    productCode: "UC-2000-VE-4T",
    category: "GSM/VoLTE Gateway",
    unitPrice: 35000,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 35000,
    retailPrice: 38500,
    endCustomerPrice: 42350,
    mrp: 46585,
  },
  {
    id: "3",
    productName: "8 Port GSM Volte Gateway",
    productCode: "UC-2000-VE-8T",
    category: "GSM/VoLTE Gateway",
    unitPrice: 61560,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 61560,
    retailPrice: 67716,
    endCustomerPrice: 74488,
    mrp: 81936,
  },
  {
    id: "4",
    productName: "16 Port GSM Volte Gateway",
    productCode: "UC-2000-VF-16T",
    category: "GSM/VoLTE Gateway",
    unitPrice: 112000,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 112000,
    retailPrice: 123200,
    endCustomerPrice: 135520,
    mrp: 149072,
  },
  {
    id: "5",
    productName: "32 Port GSM Volte Gateway",
    productCode: "UC-2000-VG-32T",
    category: "GSM/VoLTE Gateway",
    unitPrice: 150000,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 150000,
    retailPrice: 165000,
    endCustomerPrice: 181500,
    mrp: 199650,
  },
  // GSM/VoLTE Gateway Multi GSM Enterprise Series
  {
    id: "6",
    productName: "16GSM 64SIM Multi-SIM",
    productCode: "UC2000-VF-16T-V131",
    category: "Multi GSM Enterprise",
    unitPrice: 125800,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 125800,
    retailPrice: 138380,
    endCustomerPrice: 152218,
    mrp: 167440,
  },
  {
    id: "7",
    productName: "32GSM 128SIM Multi-SIM",
    productCode: "UC2000-VG-32T-V131",
    category: "Multi GSM Enterprise",
    unitPrice: 186200,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 186200,
    retailPrice: 204820,
    endCustomerPrice: 225302,
    mrp: 247832,
  },
  // DINSTAR GSM Gateway
  {
    id: "8",
    productName: "2 Port GSM Gateway G.711A/U law, G.723.1, G.729A/B",
    productCode: "UC2000F-2G",
    category: "GSM Gateway",
    unitPrice: 18400,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 18400,
    retailPrice: 20240,
    endCustomerPrice: 22264,
    mrp: 24490,
  },
  {
    id: "9",
    productName: "4 Port GSM Gateway G.711A/U law, G.723.1, G.729A/B",
    productCode: "UC2000F-4G",
    category: "GSM Gateway",
    unitPrice: 26500,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 26500,
    retailPrice: 29150,
    endCustomerPrice: 32065,
    mrp: 35272,
  },
  {
    id: "10",
    productName: "8 Port GSM Gateway G.711A/U law, G.723.1, G.729A/B",
    productCode: "UC2000F-8G",
    category: "GSM Gateway",
    unitPrice: 42000,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 42000,
    retailPrice: 46200,
    endCustomerPrice: 50820,
    mrp: 55902,
  },
  {
    id: "11",
    productName: "16 Port GSM Gateway G.711A/U law, G.723.1, G.729A/B",
    productCode: "UC2000F-16G",
    category: "GSM Gateway",
    unitPrice: 61000,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 61000,
    retailPrice: 67100,
    endCustomerPrice: 73810,
    mrp: 81191,
  },
  {
    id: "12",
    productName: "32 Port GSM Gateway G.711A/U law, G.723.1, G.729A/B",
    productCode: "UC2000F-32G",
    category: "GSM Gateway",
    unitPrice: 78750,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 78750,
    retailPrice: 86625,
    endCustomerPrice: 95288,
    mrp: 104816,
  },
  {
    id: "13",
    productName: "64 Port GSM Gateway SIP/MGCP Quad-band",
    productCode: "UC2000VH-64G",
    category: "GSM Gateway",
    unitPrice: 181800,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 181800,
    retailPrice: 199980,
    endCustomerPrice: 219978,
    mrp: 241976,
  },
  // DINSTAR FXO/FXS Gateway
  {
    id: "14",
    productName: "2 Port ATA",
    productCode: "DAG1000-2S",
    category: "FXO/FXS Gateway",
    unitPrice: 3500,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 3500,
    retailPrice: 3850,
    endCustomerPrice: 4235,
    mrp: 4659,
  },
  {
    id: "15",
    productName: "4 FXS G.711A/U law, G.723.1, G.726",
    productCode: "DAG1000-4S",
    category: "FXO/FXS Gateway",
    unitPrice: 7350,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 7350,
    retailPrice: 8085,
    endCustomerPrice: 8894,
    mrp: 9783,
  },
  {
    id: "16",
    productName: "8 FXS G.711A/U law, G.723.1, G.726",
    productCode: "DAG1000-8S",
    category: "FXO/FXS Gateway",
    unitPrice: 12600,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 12600,
    retailPrice: 13860,
    endCustomerPrice: 15246,
    mrp: 16771,
  },
  {
    id: "17",
    productName: "16 FXS G.711A/U law, G.723.1, G.726",
    productCode: "DAG2000-16S",
    category: "FXO/FXS Gateway",
    unitPrice: 21000,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 21000,
    retailPrice: 23100,
    endCustomerPrice: 25410,
    mrp: 27951,
  },
  {
    id: "18",
    productName: "24 FXS G.711A/U law, G.723.1, G.729A/B",
    productCode: "DAG2000-24S",
    category: "FXO/FXS Gateway",
    unitPrice: 24000,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 24000,
    retailPrice: 26400,
    endCustomerPrice: 29040,
    mrp: 31944,
  },
  {
    id: "19",
    productName: "32 FXS G.711A/U law, G.723.1, G.726",
    productCode: "DAG2000-32S",
    category: "FXO/FXS Gateway",
    unitPrice: 33000,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 33000,
    retailPrice: 36300,
    endCustomerPrice: 39930,
    mrp: 43923,
  },
  {
    id: "20",
    productName: "48 FXS G.711A/U law, G.723.1, G.726",
    productCode: "DAG2000-48S",
    category: "FXO/FXS Gateway",
    unitPrice: 58200,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 58200,
    retailPrice: 64020,
    endCustomerPrice: 70422,
    mrp: 77464,
  },
  // Media Gateway MTG200 Series
  {
    id: "21",
    productName: "MTG200-1E1",
    productCode: "MTG200-1E1",
    category: "Media Gateway",
    unitPrice: 48000,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 48000,
    retailPrice: 52800,
    endCustomerPrice: 58080,
    mrp: 63888,
  },
  {
    id: "22",
    productName: "MTG200-2E1",
    productCode: "MTG200-2E1",
    category: "Media Gateway",
    unitPrice: 71000,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 71000,
    retailPrice: 78100,
    endCustomerPrice: 85910,
    mrp: 94501,
  },
  // IP PBX
  {
    id: "23",
    productName: "IPPBX, 2FXO",
    productCode: "UC120",
    category: "IP PBX",
    unitPrice: 12600,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 12600,
    retailPrice: 13860,
    endCustomerPrice: 15246,
    mrp: 16771,
  },
  {
    id: "24",
    productName: "IPPBX, 2FXS+2FXO",
    productCode: "UC200",
    category: "IP PBX",
    unitPrice: 26250,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 26250,
    retailPrice: 28875,
    endCustomerPrice: 31763,
    mrp: 34939,
  },
  // SBC Series
  {
    id: "25",
    productName: "5 concurrent calls and 5 transcoding sessions",
    productCode: "SBC300-05",
    category: "SBC",
    unitPrice: 36750,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 36750,
    retailPrice: 40425,
    endCustomerPrice: 44468,
    mrp: 48914,
  },
  {
    id: "26",
    productName: "10 concurrent calls and 10 transcoding sessions",
    productCode: "SBC300-10",
    category: "SBC",
    unitPrice: 36500,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 36500,
    retailPrice: 40150,
    endCustomerPrice: 44165,
    mrp: 48582,
  },
  {
    id: "27",
    productName: "50 concurrent calls and 50 transcoding sessions",
    productCode: "SBC1000-050",
    category: "SBC",
    unitPrice: 183800,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 183800,
    retailPrice: 202180,
    endCustomerPrice: 222398,
    mrp: 244638,
  },
  {
    id: "28",
    productName: "100 concurrent calls and 100 transcoding sessions",
    productCode: "SBC1000-100",
    category: "SBC",
    unitPrice: 236250,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2023-05-05",
    status: "active",
    msp: 236250,
    retailPrice: 259875,
    endCustomerPrice: 285863,
    mrp: 314449,
  },

  // Grandstream Analog Telephone Adapters
  {
    id: "29",
    productName: "1 FXS, 1 FastEthernet",
    productCode: "HT801",
    category: "Analog Telephone Adapters",
    unitPrice: 3220,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 3220,
    retailPrice: 3974,
    endCustomerPrice: 4372,
    mrp: 7500,
  },
  {
    id: "30",
    productName: "1 FXS, 1 FastEthernet (NEW, GA mid-Oct)",
    productCode: "HT801 v2",
    category: "Analog Telephone Adapters",
    unitPrice: 2875,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 2875,
    retailPrice: 3602,
    endCustomerPrice: 3962,
    mrp: 6797,
  },
  {
    id: "31",
    productName: "2 FXS, 1 FastEthernet",
    productCode: "HT802",
    category: "Analog Telephone Adapters",
    unitPrice: 3565,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 3565,
    retailPrice: 4471,
    endCustomerPrice: 4918,
    mrp: 8437,
  },
  {
    id: "32",
    productName: "2 FXS, 2 GigE, NAT Router (NEW, GA mid-Oct)",
    productCode: "HT802 v2",
    category: "Analog Telephone Adapters",
    unitPrice: 3220,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 3220,
    retailPrice: 3974,
    endCustomerPrice: 4372,
    mrp: 7500,
  },
  {
    id: "33",
    productName: "2 FXS, 2 GigE, NAT Router",
    productCode: "HT812",
    category: "Analog Telephone Adapters",
    unitPrice: 4140,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 4140,
    retailPrice: 5216,
    endCustomerPrice: 5738,
    mrp: 9844,
  },
  {
    id: "34",
    productName: "2 FXS, 2 GigE, NAT Router (NEW, GA 1H Sep)",
    productCode: "HT812 v2",
    category: "Analog Telephone Adapters",
    unitPrice: 3680,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 3680,
    retailPrice: 4595,
    endCustomerPrice: 5055,
    mrp: 8672,
  },
  {
    id: "35",
    productName: "1 FXS, 1 FXO, 2 GigE NAT Router",
    productCode: "HT813",
    category: "Analog Telephone Adapters",
    unitPrice: 5520,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 5520,
    retailPrice: 6831,
    endCustomerPrice: 7514,
    mrp: 12890,
  },
  {
    id: "36",
    productName: "4 FXS, 2 GigE, NAT Router",
    productCode: "HT814",
    category: "Analog Telephone Adapters",
    unitPrice: 7015,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 7015,
    retailPrice: 8818,
    endCustomerPrice: 9700,
    mrp: 16640,
  },
  {
    id: "37",
    productName: "4 FXS, 2 GigE, NAT Router (NEW, GA 1H Sep)",
    productCode: "HT814 v2",
    category: "Analog Telephone Adapters",
    unitPrice: 6095,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 6095,
    retailPrice: 7700,
    endCustomerPrice: 8470,
    mrp: 14531,
  },
  {
    id: "38",
    productName: "8 FXS, 2 GigE NAT Router",
    productCode: "HT818",
    category: "Analog Telephone Adapters",
    unitPrice: 11500,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 11500,
    retailPrice: 14531,
    endCustomerPrice: 15985,
    mrp: 27421,
  },
  {
    id: "39",
    productName: "8 FXS, 2 GigE NAT Router (NEW, GA 1H Sep)",
    productCode: "HT818 v2",
    category: "Analog Telephone Adapters",
    unitPrice: 9430,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 9430,
    retailPrice: 11923,
    endCustomerPrice: 13116,
    mrp: 22500,
  },
  {
    id: "40",
    productName: "4 FXO, 1 FXS, 2 GigE PoE NAT Router (New, GA mid-Sep)",
    productCode: "HT 841",
    category: "Analog Telephone Adapters",
    unitPrice: 9775,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 9775,
    retailPrice: 12172,
    endCustomerPrice: 13389,
    mrp: 22968,
  },
  {
    id: "41",
    productName: "8 FXO, 1FXS, 2 GigE, PoE, Nat Router (New, GA mid-Sep)",
    productCode: "HT 881",
    category: "Analog Telephone Adapters",
    unitPrice: 14260,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 14260,
    retailPrice: 17885,
    endCustomerPrice: 19673,
    mrp: 33749,
  },

  // Grandstream Gateways
  {
    id: "42",
    productName: "16 FXS, 1 GigE",
    productCode: "GXW4216",
    category: "Gateways",
    unitPrice: 24380,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 24380,
    retailPrice: 30677,
    endCustomerPrice: 33745,
    mrp: 57889,
  },
  {
    id: "43",
    productName: "24 FXS, 1 GigE",
    productCode: "GXW4224",
    category: "Gateways",
    unitPrice: 34730,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 34730,
    retailPrice: 43594,
    endCustomerPrice: 47954,
    mrp: 82264,
  },
  {
    id: "44",
    productName: "32 FXS, 1 GigE",
    productCode: "GXW4232",
    category: "Gateways",
    unitPrice: 40135,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 40135,
    retailPrice: 50301,
    endCustomerPrice: 55331,
    mrp: 94920,
  },
  {
    id: "45",
    productName: "48 FXS, 1 GigE",
    productCode: "GXW4248",
    category: "Gateways",
    unitPrice: 60375,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 60375,
    retailPrice: 75638,
    endCustomerPrice: 83202,
    mrp: 142731,
  },
  {
    id: "46",
    productName: "16 FXS, 1 GigE, GDMS Compatible",
    productCode: "GXW4216V2",
    category: "Gateways",
    unitPrice: 28290,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 28290,
    retailPrice: 35521,
    endCustomerPrice: 39073,
    mrp: 67030,
  },
  {
    id: "47",
    productName: "24 FXS, 1 GigE, GDMS Compatible",
    productCode: "GXW4224V2",
    category: "Gateways",
    unitPrice: 41170,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 41170,
    retailPrice: 51667,
    endCustomerPrice: 56834,
    mrp: 97498,
  },
  {
    id: "48",
    productName: "32 FXS, 1 GigE, GDMS Compatible",
    productCode: "GXW4232V2",
    category: "Gateways",
    unitPrice: 48990,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 48990,
    retailPrice: 61479,
    endCustomerPrice: 67627,
    mrp: 116013,
  },
  {
    id: "49",
    productName: "48 FXS, 1 GigE, GDMS Compatible",
    productCode: "GXW4248V2",
    category: "Gateways",
    unitPrice: 72105,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 72105,
    retailPrice: 90418,
    endCustomerPrice: 99459,
    mrp: 170621,
  },

  // Grandstream IP-PBX
  {
    id: "50",
    productName: "0 FXO, 0 FXS, 250 Users *NO VIDEO Conferencing*",
    productCode: "UCM6300A",
    category: "IP-PBX",
    unitPrice: 12995,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 12995,
    retailPrice: 16270,
    endCustomerPrice: 17897,
    mrp: 30702,
  },
  {
    id: "51",
    productName: "2 FXO, 2 FXS, 500 Users *NO VIDEO Conferencing*",
    productCode: "UCM6302A",
    category: "IP-PBX",
    unitPrice: 22770,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 22770,
    retailPrice: 28566,
    endCustomerPrice: 31423,
    mrp: 53905,
  },
  {
    id: "52",
    productName: "4 FXO, 4 FXS, 1000 Users *NO VIDEO Conferencing*",
    productCode: "UCM6304A",
    category: "IP-PBX",
    unitPrice: 36800,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 36800,
    retailPrice: 46078,
    endCustomerPrice: 50686,
    mrp: 86951,
  },
  {
    id: "53",
    productName: "8 FXO, 8 FXS, 1500 Users *NO VIDEO Conferencing*",
    productCode: "UCM6308A",
    category: "IP-PBX",
    unitPrice: 59455,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 59455,
    retailPrice: 74520,
    endCustomerPrice: 81972,
    mrp: 140622,
  },
  {
    id: "54",
    productName: "1 FXO, 1FXS, 500 Users",
    productCode: "UCM6301",
    category: "IP-PBX",
    unitPrice: 20010,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 20010,
    retailPrice: 25088,
    endCustomerPrice: 27597,
    mrp: 47343,
  },
  {
    id: "55",
    productName: "2 FXO, 2FXS, 1000 Users",
    productCode: "UCM6302",
    category: "IP-PBX",
    unitPrice: 26450,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 26450,
    retailPrice: 33161,
    endCustomerPrice: 36478,
    mrp: 62577,
  },
  {
    id: "56",
    productName: "4 FXO, 4 FXS, 2500 Users",
    productCode: "UCM6304",
    category: "IP-PBX",
    unitPrice: 60145,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 60145,
    retailPrice: 75389,
    endCustomerPrice: 82928,
    mrp: 142263,
  },
  {
    id: "57",
    productName: "8 FXO, 8 FXS 5000 Users",
    productCode: "UCM6308",
    category: "IP-PBX",
    unitPrice: 80040,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 80040,
    retailPrice: 100354,
    endCustomerPrice: 110389,
    mrp: 189371,
  },

  // Grandstream UCMRC Plans
  {
    id: "58",
    productName: "Up to 20 Remote Users & 4 Remote Calls",
    productCode: "UCMRC SOHO",
    category: "UCMRC Plans",
    unitPrice: 7935,
    currency: "INR",
    unit: "license",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 7935,
    retailPrice: 9936,
    endCustomerPrice: 10930,
    mrp: 18750,
  },
  {
    id: "59",
    productName: "8 Concurrent Voice/Video Calls, 50 Registered Users, 1 GB Cloud Storage",
    productCode: "UCMRC Plus",
    category: "UCMRC Plans",
    unitPrice: 11155,
    currency: "INR",
    unit: "license",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 11155,
    retailPrice: 14035,
    endCustomerPrice: 15438,
    mrp: 26484,
  },
  {
    id: "60",
    productName: "16 Concurrent Voice/Video Calls, 100 Registered Users, 2 GB Cloud Storage",
    productCode: "UCMRC Pro",
    category: "UCMRC Plans",
    unitPrice: 17020,
    currency: "INR",
    unit: "license",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 17020,
    retailPrice: 21362,
    endCustomerPrice: 23499,
    mrp: 40312,
  },
  {
    id: "61",
    productName: "32 Concurrent Voice/Video Calls, 200 Registered Users, 5 GB Cloud Storage",
    productCode: "UCMRC Business",
    category: "UCMRC Plans",
    unitPrice: 24380,
    currency: "INR",
    unit: "license",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 24380,
    retailPrice: 30677,
    endCustomerPrice: 33745,
    mrp: 57889,
  },
  {
    id: "62",
    productName: "64 Concurrent Voice/Video Calls, 400 Registered Users, 10 GB Cloud Storage",
    productCode: "UCMRC Enterprise",
    category: "UCMRC Plans",
    unitPrice: 42320,
    currency: "INR",
    unit: "license",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 42320,
    retailPrice: 53033,
    endCustomerPrice: 58337,
    mrp: 100076,
  },

  // Grandstream Wireless IP Phones
  {
    id: "63",
    productName: "HD DECT Handset",
    productCode: "DP720",
    category: "Wireless IP Phones",
    unitPrice: 4025,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 4025,
    retailPrice: 5092,
    endCustomerPrice: 5601,
    mrp: 9609,
  },
  {
    id: "64",
    productName: "HD DECT Base Station",
    productCode: "DP750",
    category: "Wireless IP Phones",
    unitPrice: 3795,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 3795,
    retailPrice: 4844,
    endCustomerPrice: 5328,
    mrp: 9140,
  },
  {
    id: "65",
    productName: "HD Mid-Tier DECT Handset",
    productCode: "DP722",
    category: "Wireless IP Phones",
    unitPrice: 4025,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 4025,
    retailPrice: 5092,
    endCustomerPrice: 5601,
    mrp: 9609,
  },
  {
    id: "66",
    productName: "HD Compact DECT Handset",
    productCode: "DP725",
    category: "Wireless IP Phones",
    unitPrice: 4025,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 4025,
    retailPrice: 5092,
    endCustomerPrice: 5601,
    mrp: 9609,
  },
  {
    id: "67",
    productName: "HD High-Tier DECT Handset",
    productCode: "DP730",
    category: "Wireless IP Phones",
    unitPrice: 6555,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 6555,
    retailPrice: 8197,
    endCustomerPrice: 9017,
    mrp: 15468,
  },
  {
    id: "68",
    productName: "Ruggedized High-Tier DECT Handset",
    productCode: "DP735",
    category: "Wireless IP Phones",
    unitPrice: 6555,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 6555,
    retailPrice: 8197,
    endCustomerPrice: 9017,
    mrp: 15468,
  },
  {
    id: "69",
    productName: "Portable WiFi Phone",
    productCode: "WP810",
    category: "Wireless IP Phones",
    unitPrice: 6095,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 6095,
    retailPrice: 7700,
    endCustomerPrice: 8470,
    mrp: 14531,
  },
  {
    id: "70",
    productName: "Compact Portable WiFi Phone",
    productCode: "WP816",
    category: "Wireless IP Phones",
    unitPrice: 5060,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 5060,
    retailPrice: 6458,
    endCustomerPrice: 7104,
    mrp: 12187,
  },
  {
    id: "71",
    productName: "Enterprise Portable WiFI Phone",
    productCode: "WP820",
    category: "Wireless IP Phones",
    unitPrice: 9660,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 9660,
    retailPrice: 12047,
    endCustomerPrice: 13252,
    mrp: 22734,
  },

  // Grandstream HD IP Phones
  {
    id: "72",
    productName: "1 Line, 1 SIP Account",
    productCode: "GXP1610",
    category: "HD IP Phones",
    unitPrice: 2530,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 2530,
    retailPrice: 3229,
    endCustomerPrice: 3552,
    mrp: 6094,
  },
  {
    id: "73",
    productName: "1 Line, 1 SIP Account, PoE, no PSU",
    productCode: "GXP1610P",
    category: "HD IP Phones",
    unitPrice: 2530,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 2530,
    retailPrice: 3229,
    endCustomerPrice: 3552,
    mrp: 6094,
  },
  {
    id: "74",
    productName: "1 Line, 1 SIP Account, PoE",
    productCode: "GXP1615",
    category: "HD IP Phones",
    unitPrice: 2760,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 2760,
    retailPrice: 3478,
    endCustomerPrice: 3825,
    mrp: 6562,
  },
  {
    id: "75",
    productName: "2 Lines, 2 SIP Accounts",
    productCode: "GXP1620",
    category: "HD IP Phones",
    unitPrice: 2760,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 2760,
    retailPrice: 3478,
    endCustomerPrice: 3825,
    mrp: 6562,
  },
  {
    id: "76",
    productName: "2 Lines, 2 SIP Accounts, PoE",
    productCode: "GXP1625",
    category: "HD IP Phones",
    unitPrice: 3220,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 3220,
    retailPrice: 3974,
    endCustomerPrice: 4372,
    mrp: 7500,
  },
  {
    id: "77",
    productName: "2 Lines, 2 SIP Accounts, PoE + GigE, 8 BLF",
    productCode: "GXP1628",
    category: "HD IP Phones",
    unitPrice: 4485,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 4485,
    retailPrice: 5589,
    endCustomerPrice: 6148,
    mrp: 10547,
  },
  {
    id: "78",
    productName: "3 Lines, 3 SIP Accounts, PoE + GigE, 8 BLF",
    productCode: "GXP1630",
    category: "HD IP Phones",
    unitPrice: 4715,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 4715,
    retailPrice: 5962,
    endCustomerPrice: 6558,
    mrp: 11250,
  },
  {
    id: "79",
    productName: "3 Lines, 3 SIP Accounts, PoE + GigE, Color",
    productCode: "GXP2130",
    category: "HD IP Phones",
    unitPrice: 7015,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 7015,
    retailPrice: 8818,
    endCustomerPrice: 9700,
    mrp: 16640,
  },
  {
    id: "80",
    productName: "8 Lines, 4 SIP Accounts, PoE + GigE, Color",
    productCode: "GXP2135",
    category: "HD IP Phones",
    unitPrice: 7015,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 7015,
    retailPrice: 8818,
    endCustomerPrice: 9700,
    mrp: 16640,
  },

  // Grandstream Networking Products
  {
    id: "81",
    productName: "Multi-WAN Gigabit VPN Router, 6 x GigE",
    productCode: "GWN7001",
    category: "Networking Products",
    unitPrice: 3795,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 3795,
    retailPrice: 4844,
    endCustomerPrice: 5328,
    mrp: 9140,
  },
  {
    id: "82",
    productName: "Multi-WAN Gigabit VPN Router, 4 x GigE, 2 x SFP",
    productCode: "GWN7002",
    category: "Networking Products",
    unitPrice: 4485,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 4485,
    retailPrice: 5589,
    endCustomerPrice: 6148,
    mrp: 10547,
  },
  {
    id: "83",
    productName: "Multi-WAN Gigabit VPN Router, 9 x GigE, 2 x SFP",
    productCode: "GWN7003",
    category: "Networking Products",
    unitPrice: 6670,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 6670,
    retailPrice: 8321,
    endCustomerPrice: 9154,
    mrp: 15703,
  },
  {
    id: "84",
    productName: "2x2 802.11ac Wave-2 WiFi ROUTER with 4 LAN + 1 WAN GigE",
    productCode: "GWN7052",
    category: "Networking Products",
    unitPrice: 2990,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 2990,
    retailPrice: 3850,
    endCustomerPrice: 4235,
    mrp: 7265,
  },
  {
    id: "85",
    productName: "2x2 802.11ac Wave-2 WiFi ROUTER with 3 LAN+ 1(wan/lan) + 1 WAN SFP",
    productCode: "GWN7052F",
    category: "Networking Products",
    unitPrice: 4715,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 4715,
    retailPrice: 5962,
    endCustomerPrice: 6558,
    mrp: 11250,
  },
  {
    id: "86",
    productName: "2x2 802.11ax WiFi ROUTER with 3 LAN + 1 LAN/WAN + 1 WAN GigE",
    productCode: "GWN7062",
    category: "Networking Products",
    unitPrice: 5750,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 5750,
    retailPrice: 7204,
    endCustomerPrice: 7924,
    mrp: 13593,
  },
  {
    id: "87",
    productName: "2x2 802.11ac Wave-2 Wi-Fi 5 AP With Integrated Ethernet Switch",
    productCode: "GWN7602",
    category: "Networking Products",
    unitPrice: 4255,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 4255,
    retailPrice: 5341,
    endCustomerPrice: 5875,
    mrp: 10078,
  },
  {
    id: "88",
    productName: "2x2 802.11ac Wave-2 Wi-Fi 5 AP With Integrated Ethernet Switch",
    productCode: "GWN7603",
    category: "Networking Products",
    unitPrice: 4140,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 4140,
    retailPrice: 5216,
    endCustomerPrice: 5738,
    mrp: 9844,
  },
  {
    id: "89",
    productName: "2x2 802.11ac Wave-2 Wi-Fi 5 AP (100+ clients), 165 mtr range, 1.27Gbps",
    productCode: "GWN7605",
    category: "Networking Products",
    unitPrice: 4945,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 4945,
    retailPrice: 6210,
    endCustomerPrice: 6831,
    mrp: 11719,
  },
  {
    id: "90",
    productName: "2x2 802.11ac Wave-2 Wi-Fi 5 Outdoor Long Range AP",
    productCode: "GWN7605LR",
    category: "Networking Products",
    unitPrice: 6900,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 6900,
    retailPrice: 8694,
    endCustomerPrice: 9563,
    mrp: 16406,
  },

  // Continue with more networking products, switches, etc.
  {
    id: "91",
    productName: "Unmanaged Network Switch, 5 x GigE",
    productCode: "GWN7700",
    category: "Network Switches",
    unitPrice: 690,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 690,
    retailPrice: 869,
    endCustomerPrice: 956,
    mrp: 1641,
  },
  {
    id: "92",
    productName: "Unmanaged Network Switch, 5 x GigE (4 x PoE)",
    productCode: "GWN7700P",
    category: "Network Switches",
    unitPrice: 2415,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 2415,
    retailPrice: 2981,
    endCustomerPrice: 3279,
    mrp: 5625,
  },
  {
    id: "93",
    productName: "Unmanaged Network Switch, 8 x GigE",
    productCode: "GWN7701",
    category: "Network Switches",
    unitPrice: 1150,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 1150,
    retailPrice: 1490,
    endCustomerPrice: 1639,
    mrp: 2812,
  },
  {
    id: "94",
    productName: "Unmanaged Network Switch, 8 x GigE (4 x PoE)",
    productCode: "GWN7701P",
    category: "Network Switches",
    unitPrice: 3105,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 3105,
    retailPrice: 3850,
    endCustomerPrice: 4235,
    mrp: 7265,
  },
  {
    id: "95",
    productName: "Unmanaged Network Switch, 16 x GigE",
    productCode: "GWN7702",
    category: "Network Switches",
    unitPrice: 4600,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 4600,
    retailPrice: 5713,
    endCustomerPrice: 6285,
    mrp: 10781,
  },
  {
    id: "96",
    productName: "Unmanaged Network Switch, 24 x GigE",
    productCode: "GWN7703",
    category: "Network Switches",
    unitPrice: 5520,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 5520,
    retailPrice: 6831,
    endCustomerPrice: 7514,
    mrp: 12890,
  },
  {
    id: "97",
    productName: "Enterprise Layer 2+ Managed Network Switch, 8 x GigE, 2 x SFP",
    productCode: "GWN7801",
    category: "Managed Switches",
    unitPrice: 6555,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 6555,
    retailPrice: 8197,
    endCustomerPrice: 9017,
    mrp: 15468,
  },
  {
    id: "98",
    productName: "Enterprise Layer 2+ Managed PoE Network Switch, 8 x GigE, 2 x SFP",
    productCode: "GWN7801P",
    category: "Managed Switches",
    unitPrice: 9660,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 9660,
    retailPrice: 12047,
    endCustomerPrice: 13252,
    mrp: 22734,
  },
  {
    id: "99",
    productName: "Enterprise Layer 2+ Managed Network Switch, 16 x GigE, 4 x SFP",
    productCode: "GWN7802",
    category: "Managed Switches",
    unitPrice: 10580,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 10580,
    retailPrice: 13289,
    endCustomerPrice: 14618,
    mrp: 25078,
  },
  {
    id: "100",
    productName: "Enterprise Layer 2+ Managed Network Switch, 24 x GigE, 4 x SFP",
    productCode: "GWN7803",
    category: "Managed Switches",
    unitPrice: 12305,
    currency: "INR",
    unit: "piece",
    lastUpdated: "2025-04-30",
    status: "active",
    msp: 12305,
    retailPrice: 15401,
    endCustomerPrice: 16941,
    mrp: 29062,
  },
]

export default function PricelistPage() {
  const [searchTerm, setSearchTerm] = useState("")
  const [selectedCategory, setSelectedCategory] = useState("all")
  const [pricelistItems, setPricelistItems] = useState<PricelistItem[]>(mockPricelistData)

  const categories = ["all", ...Array.from(new Set(mockPricelistData.map((item) => item.category)))]

  const filteredItems = pricelistItems.filter((item) => {
    const matchesSearch =
      item.productName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      item.productCode.toLowerCase().includes(searchTerm.toLowerCase())
    const matchesCategory = selectedCategory === "all" || item.category === selectedCategory
    return matchesSearch && matchesCategory
  })

  const formatCurrency = (amount: number, currency: string) => {
    return new Intl.NumberFormat("en-IN", {
      style: "currency",
      currency: currency,
      minimumFractionDigits: 2,
    }).format(amount)
  }

  return (
    <AdminLayout>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex justify-between items-center">
          <div>
            <h1 className="text-3xl font-bold text-gray-900">Pricelist Management</h1>
            <p className="text-gray-600 mt-1">Manage product prices and pricing information</p>
          </div>
          <Button className="flex items-center gap-2">
            <Plus className="w-4 h-4" />
            Add New Item
          </Button>
        </div>

        {/* Filters and Search */}
        <Card>
          <CardContent className="p-6">
            <div className="flex flex-col sm:flex-row gap-4">
              <div className="flex-1">
                <div className="relative">
                  <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-4 h-4" />
                  <Input
                    placeholder="Search by product name or code..."
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    className="pl-10"
                  />
                </div>
              </div>
              <div className="flex gap-2">
                <select
                  value={selectedCategory}
                  onChange={(e) => setSelectedCategory(e.target.value)}
                  className="px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  {categories.map((category) => (
                    <option key={category} value={category}>
                      {category === "all" ? "All Categories" : category}
                    </option>
                  ))}
                </select>
                <Button variant="outline" size="sm">
                  <Filter className="w-4 h-4 mr-2" />
                  Filter
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Statistics Cards */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium text-gray-600">Total Items</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{pricelistItems.length}</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium text-gray-600">Active Items</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-green-600">
                {pricelistItems.filter((item) => item.status === "active").length}
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium text-gray-600">Categories</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{categories.length - 1}</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium text-gray-600">Avg. Price</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">
                {formatCurrency(
                  pricelistItems.reduce((sum, item) => sum + item.unitPrice, 0) / pricelistItems.length,
                  "INR",
                )}
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Pricelist Table */}
        <Card>
          <CardHeader>
            <CardTitle>Price List ({filteredItems.length} items)</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="border-b">
                    <th className="text-left py-3 px-4 font-medium text-gray-600">Product</th>
                    <th className="text-left py-3 px-4 font-medium text-gray-600">Code</th>
                    <th className="text-left py-3 px-4 font-medium text-gray-600">Category</th>
                    <th className="text-right py-3 px-4 font-medium text-gray-600">MSP</th>
                    <th className="text-right py-3 px-4 font-medium text-gray-600">Retail Price</th>
                    <th className="text-right py-3 px-4 font-medium text-gray-600">End Customer</th>
                    <th className="text-right py-3 px-4 font-medium text-gray-600">MRP</th>
                    <th className="text-left py-3 px-4 font-medium text-gray-600">Status</th>
                    <th className="text-right py-3 px-4 font-medium text-gray-600">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {filteredItems.map((item) => (
                    <tr key={item.id} className="border-b hover:bg-gray-50">
                      <td className="py-3 px-4">
                        <div className="font-medium text-gray-900">{item.productName}</div>
                        <div className="text-sm text-gray-500">{item.category}</div>
                      </td>
                      <td className="py-3 px-4">
                        <code className="bg-gray-100 px-2 py-1 rounded text-sm">{item.productCode}</code>
                      </td>
                      <td className="py-3 px-4">
                        <span className="text-sm text-gray-600">{item.category}</span>
                      </td>
                      <td className="py-3 px-4 text-right">
                        <span className="font-medium">{formatCurrency(item.msp || item.unitPrice, item.currency)}</span>
                      </td>
                      <td className="py-3 px-4 text-right">
                        <span className="font-medium">
                          {formatCurrency(item.retailPrice || item.unitPrice, item.currency)}
                        </span>
                      </td>
                      <td className="py-3 px-4 text-right">
                        <span className="font-medium">
                          {formatCurrency(item.endCustomerPrice || item.unitPrice, item.currency)}
                        </span>
                      </td>
                      <td className="py-3 px-4 text-right">
                        <span className="font-medium">{formatCurrency(item.mrp || item.unitPrice, item.currency)}</span>
                      </td>
                      <td className="py-3 px-4">
                        <Badge variant={item.status === "active" ? "default" : "secondary"}>{item.status}</Badge>
                      </td>
                      <td className="py-3 px-4">
                        <div className="flex justify-end gap-2">
                          <Button variant="ghost" size="sm">
                            <Edit className="w-4 h-4" />
                          </Button>
                          <Button variant="ghost" size="sm" className="text-red-600 hover:text-red-700">
                            <Trash2 className="w-4 h-4" />
                          </Button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {filteredItems.length === 0 && (
              <div className="text-center py-8">
                <p className="text-gray-500">No items found matching your search criteria.</p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </AdminLayout>
  )
}
